/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseErrMsg: typeof import('./components/share/err-msg/BaseErrMsg.vue')['default']
    BaseForm: typeof import('./components/share/form/BaseForm.vue')['default']
    BaseInput: typeof import('./components/share/input/BaseInput.vue')['default']
    ButtonFill: typeof import('./components/share/button/ButtonFill.vue')['default']
    ButtonPost: typeof import('./components/share/button/ButtonPost.vue')['default']
    ButtonPrimary: typeof import('./components/share/button/ButtonPrimary.vue')['default']
    ButtonSuccess: typeof import('./components/share/button/ButtonSuccess.vue')['default']
    DoSomething: typeof import('./components/Home/DoSomething.vue')['default']
    Feeling: typeof import('./components/Home/Feeling.vue')['default']
    Footer: typeof import('./components/Footer/Footer.vue')['default']
    Life: typeof import('./components/Home/Life.vue')['default']
    LoginModal: typeof import('./components/share/modal/login/LoginModal.vue')['default']
    Modal: typeof import('./components/share/modal/Modal.vue')['default']
    NavBar: typeof import('./components/NavBar/NavBar.vue')['default']
    RegisterModal: typeof import('./components/share/modal/register/RegisterModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skill: typeof import('./components/Home/Skill.vue')['default']
    Test: typeof import('./components/Test.vue')['default']
    TextBody2: typeof import('./components/share/literal/TextBody2.vue')['default']
    TextBodyTitle: typeof import('./components/share/literal/TextBodyTitle.vue')['default']
  }
}
